### PR TITLE
added date time skills

### PR DESCRIPTION
**Pull request by iriyagupta**
Will add the comments soon ofr the file!

### CODE REVIEW

**Review by siddeshshewde — COMMENTED** [review]
The skeleton looks good to me. So couple of changes:
1. Instead of print, I would want the AI to speak the time.
2. I was thinking maybe the AI could say something like:
    - 12 o clock 
    - Quarter past 12
    - Quarter to 12
    - Half Past 12
    - x minutes to 12
    - x minutes past 12

We can use ifelse to achieve this or maybe you might have a better solution?
Let me know your thoughts.

**Comment by iriyagupta** [comment]
@siddeshshewde hey, just adding the voice output haha. Sorry I wrote comment but forgot to post it here

**Comment by iriyagupta** [comment]
@siddeshshewde Hi, check the code once, I have added the voice assistant where it speaks the time, day, date etc and takes the input from the user in voice as well for the timezones. I hope that works.

**Comment by siddeshshewde** [comment]
Damn! Night coder.
I'll check it out tomorrow

**Comment by iriyagupta** [comment]
@siddeshshewde  were you  able to check?

**Review by siddeshshewde — APPROVED** [review]

**Comment by siddeshshewde** [comment]
Works like a charm! (y)
Only thing is I wanted the 'text to audio / audio to text' to be taken from Engine folder. But I think ill do it for now.
Thanks!

**Pull request merged**
